apiVersion: v1
kind: Pod
metadata:
  name: fluent-bit-with-sidecar
  namespace: kube-system
spec:
  serviceAccountName: fluent-bit
  volumes:
    - name: log-file
      gitRepo:
        repository: https://github.com/Abdelmounaim-Azz/test.git
        revision: main
        directory: .
    - name: fluent-bit-config
      configMap:
        name: fluent-bit-config
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
  terminationGracePeriodSeconds: 10
  containers:
    - name: fluent-bit
      image: fluent/fluent-bit:1.5-debug
      command:
        - /fluent-bit/bin/fluent-bit
        - -c
        - /fluent-bit/etc/fluent-bit.conf
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
      volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: log-file
          mountPath: /log-file/
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
    - name: sidecar-container
      image: busybox
      command:
        [
          "sh",
          "-c",
          "while true; do cat /var/log/test.log /var/log/error.log; sleep 30; done",
        ]
      volumeMounts:
        - name: log-file
          mountPath: /var/log/
